service: excel-report-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 1024
  timeout: 300
  
  environment:
    NODE_ENV: ${self:provider.stage}
    SERVICE_VERSION: ${self:service}-${self:provider.stage}-v1.0.0
    LOG_LEVEL: ${self:custom.logLevel.${self:provider.stage}, 'INFO'}
    BUCKET: ${env:BUCKET}
    IMAGES_BUCKET: ${env:IMAGES_BUCKET, ''}
    AWS_REGION: ${self:provider.region}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
            - s3:ListBucket
          Resource:
            - arn:aws:s3:::${env:BUCKET}
            - arn:aws:s3:::${env:BUCKET}/*
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: arn:aws:logs:${self:provider.region}:*:*

custom:
  logLevel:
    dev: DEBUG
    prod: INFO

functions:
  generateReport:
    handler: src/handlers/lambda-handler.handler
    description: Generates Excel reports from S3 data
    events:
      - http:
          path: /generate-report
          method: post
          cors: true
    reservedConcurrency: 5
    
  healthCheck:
    handler: src/handlers/lambda-handler.healthCheck
    description: Health check endpoint
    events:
      - http:
          path: /health
          method: get
          cors: true

plugins:
  - serverless-offline

package:
  exclude:
    - test/**
    - scripts/**
    - .git/**
    - .env*
    - README.md
    - '*.test.js'