service: report-excel-lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs22.x
  stage: ${opt:stage, 'prod'}
  region: ${env:REGION, 'us-west-2'}
  memorySize: 4096
  timeout: 600

  environment:
    NODE_ENV: ${env:NODE_ENV, 'production'}
    SERVICE_VERSION: report-excel-lambda-v1.0.0
    LOG_LEVEL: ${env:LOG_LEVEL, 'INFO'}
    BUCKET: ${env:BUCKET}
    IMAGES_BUCKET: ${env:IMAGES_BUCKET}
    IMAGES_REGION: ${env:IMAGES_REGION, 'us-east-1'}
    REGION: ${env:REGION, 'us-west-2'}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
            - s3:ListBucket
          Resource:
            - arn:aws:s3:::${env:BUCKET}
            - arn:aws:s3:::${env:BUCKET}/*
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: arn:aws:logs:${self:provider.region}:*:*

functions:
  main:
    name: report-excel-lambda
    handler: src/handlers/lambda-handler.handler
    description: Generates Excel reports from S3 data
    events:
      - http:
          path: /generate-report
          method: post
          cors: true
      - http:
          path: /health
          method: get
          cors: true
    reservedConcurrency: 5

plugins:
  - serverless-offline

package:
  exclude:
    - test/**
    - scripts/**
    - .git/**
    - .env*
    - README.md
    - '*.test.js'
