name: Deploy Lambda Function

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force deployment even if tests fail'
        required: false
        default: false
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.inputs.force_deploy != 'true'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Run tests
      run: yarn test
      env:
        NODE_ENV: test

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    if: always() && (needs.test.result == 'success' || github.event.inputs.force_deploy == 'true')
    
    environment:
      name: production
      url: ${{ steps.deploy.outputs.endpoint }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.REGION || 'us-west-2' }}
    
    - name: Deploy to AWS Lambda
      id: deploy
      run: |
        node scripts/deploy.js
        echo "endpoint=https://$(aws apigateway get-rest-apis --region ${{ vars.REGION || 'us-west-2' }} --query 'items[?name==`report-excel-lambda-prod`].id' --output text).execute-api.${{ vars.REGION || 'us-west-2' }}.amazonaws.com/prod" >> $GITHUB_OUTPUT
      env:
        LAMBDA_FUNCTION_NAME: report-excel-lambda
        REGION: ${{ vars.REGION || 'us-west-2' }}
        BUCKET: ${{ vars.BUCKET }}
        IMAGES_BUCKET: ${{ vars.IMAGES_BUCKET }}
        IMAGES_REGION: us-east-1
        JOBS_TABLE: ${{ vars.JOBS_TABLE || 'excel-report-jobs' }}
        JOB_TTL_HOURS: ${{ vars.JOB_TTL_HOURS || '24' }}
        NODE_ENV: production
        LOG_LEVEL: INFO
    
    - name: Run post-deployment health check
      run: |
        # Wait for Lambda to be ready
        sleep 10
        
        # Test health check endpoint (if API Gateway is available)
        ENDPOINT="${{ steps.deploy.outputs.endpoint }}"
        if [ ! -z "$ENDPOINT" ] && [ "$ENDPOINT" != "https://.execute-api.${{ vars.REGION || 'us-west-2' }}.amazonaws.com/prod" ]; then
          echo "Testing health check endpoint: $ENDPOINT/health"
          for i in {1..3}; do
            if curl -f "${ENDPOINT}/health"; then
              echo "Health check passed on attempt $i"
              break
            elif [ $i -eq 3 ]; then
              echo "Health check failed after 3 attempts, but Lambda deployment succeeded"
              break
            else
              echo "Health check failed on attempt $i, retrying in 10s..."
              sleep 10
            fi
          done
        else
          echo "API Gateway endpoint not found, skipping health check"
          echo "Lambda function deployment completed successfully"
        fi
    
    - name: Notify deployment status
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "🚀 Lambda deployment successful!"
          echo "Function: report-excel-lambda"
          echo "Endpoint: ${{ steps.deploy.outputs.endpoint }}"
        else
          echo "💥 Lambda deployment failed!"
          exit 1
        fi